apiVersion: apps/v1
kind: Deployment
metadata:
  name: catcher
  labels:
    app: catcher
  namespace: foghorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catcher
  template:
    metadata:
      labels:
        app: catcher
    spec:
      containers:
      - name: catcher
        image: github.com/foghornci/foghorn/cmd/catcher
        ports:
        - containerPort: 8080
